/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FepocDropDownComponent {
        "displayprops": string[];
        "options": any[];
        "placeholder"?: string;
    }
    interface FepocModal {
        "content": string;
        "header": string;
        "open": string;
        "primarybutton": string;
        "secondarybutton": string;
    }
    interface FepocTooltip {
        "HoverText": string;
        "displayText": string;
        "hoverLength": number;
    }
    interface GbrPagination {
        "datalist": any[];
        "pagesize": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface FepocDropDownComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFepocDropDownComponentElement;
}
export interface FepocModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFepocModalElement;
}
export interface GbrPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGbrPaginationElement;
}
declare global {
    interface HTMLFepocDropDownComponentElementEventMap {
        "selectedOptionEvent": any;
    }
    interface HTMLFepocDropDownComponentElement extends Components.FepocDropDownComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFepocDropDownComponentElementEventMap>(type: K, listener: (this: HTMLFepocDropDownComponentElement, ev: FepocDropDownComponentCustomEvent<HTMLFepocDropDownComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFepocDropDownComponentElementEventMap>(type: K, listener: (this: HTMLFepocDropDownComponentElement, ev: FepocDropDownComponentCustomEvent<HTMLFepocDropDownComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFepocDropDownComponentElement: {
        prototype: HTMLFepocDropDownComponentElement;
        new (): HTMLFepocDropDownComponentElement;
    };
    interface HTMLFepocModalElementEventMap {
        "closeType": string;
    }
    interface HTMLFepocModalElement extends Components.FepocModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFepocModalElementEventMap>(type: K, listener: (this: HTMLFepocModalElement, ev: FepocModalCustomEvent<HTMLFepocModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFepocModalElementEventMap>(type: K, listener: (this: HTMLFepocModalElement, ev: FepocModalCustomEvent<HTMLFepocModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFepocModalElement: {
        prototype: HTMLFepocModalElement;
        new (): HTMLFepocModalElement;
    };
    interface HTMLFepocTooltipElement extends Components.FepocTooltip, HTMLStencilElement {
    }
    var HTMLFepocTooltipElement: {
        prototype: HTMLFepocTooltipElement;
        new (): HTMLFepocTooltipElement;
    };
    interface HTMLGbrPaginationElementEventMap {
        "paginatedlisthandler": any[];
    }
    interface HTMLGbrPaginationElement extends Components.GbrPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGbrPaginationElementEventMap>(type: K, listener: (this: HTMLGbrPaginationElement, ev: GbrPaginationCustomEvent<HTMLGbrPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGbrPaginationElementEventMap>(type: K, listener: (this: HTMLGbrPaginationElement, ev: GbrPaginationCustomEvent<HTMLGbrPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGbrPaginationElement: {
        prototype: HTMLGbrPaginationElement;
        new (): HTMLGbrPaginationElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fepoc-drop-down-component": HTMLFepocDropDownComponentElement;
        "fepoc-modal": HTMLFepocModalElement;
        "fepoc-tooltip": HTMLFepocTooltipElement;
        "gbr-pagination": HTMLGbrPaginationElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FepocDropDownComponent {
        "displayprops"?: string[];
        "onSelectedOptionEvent"?: (event: FepocDropDownComponentCustomEvent<any>) => void;
        "options"?: any[];
        "placeholder"?: string;
    }
    interface FepocModal {
        "content"?: string;
        "header"?: string;
        "onCloseType"?: (event: FepocModalCustomEvent<string>) => void;
        "open"?: string;
        "primarybutton"?: string;
        "secondarybutton"?: string;
    }
    interface FepocTooltip {
        "HoverText"?: string;
        "displayText"?: string;
        "hoverLength"?: number;
    }
    interface GbrPagination {
        "datalist"?: any[];
        "onPaginatedlisthandler"?: (event: GbrPaginationCustomEvent<any[]>) => void;
        "pagesize"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fepoc-drop-down-component": FepocDropDownComponent;
        "fepoc-modal": FepocModal;
        "fepoc-tooltip": FepocTooltip;
        "gbr-pagination": GbrPagination;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fepoc-drop-down-component": LocalJSX.FepocDropDownComponent & JSXBase.HTMLAttributes<HTMLFepocDropDownComponentElement>;
            "fepoc-modal": LocalJSX.FepocModal & JSXBase.HTMLAttributes<HTMLFepocModalElement>;
            "fepoc-tooltip": LocalJSX.FepocTooltip & JSXBase.HTMLAttributes<HTMLFepocTooltipElement>;
            "gbr-pagination": LocalJSX.GbrPagination & JSXBase.HTMLAttributes<HTMLGbrPaginationElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
